### PR TITLE
Polling to update notification count

### PR DESCRIPTION
**Pull request by mouse-reeve**
I considered adding a live region but I think it would be too annoying (at least without also adding settings to disable it)?

### CODE REVIEW

**Comment by rkingett** [comment]
How about making it a default browser notification instead of a live region? I'm not too wild about the live region because I am worried it would interrupt NVDA. That being said, what about a default browser notification toggle?

**Comment by mouse-reeve** [comment]
hm, desktop notifications seem aggressive for an application that never reasonably needs to grab anyone's attention. But there's not any harm in making them opt-in. Do you prefer them to notification sounds?

**Comment by rkingett** [comment]
I actually would prefer notification sounds rather than browser notifications, now that I think about it, but yes. Making these opt in would be best.

**Comment by mouse-reeve** [comment]
rad, that's my preference as well. I'm going to merge this change and add that in a separate PR once I find a ding I like.

**Pull request merged**
