### PR TITLE
Use sorted set for activitystreams

### LINKED ISSUE #853: Goodreads import floods activity streams
When a user does a goodreads import, the activitstreams manager isn't checking if the publication date is older than the oldest status, and adds all the statuses to the feeds, pushing out newer statuses.

### PR DESCRIPTION
**Pull request by mouse-reeve**
Fixes #853

### CODE REVIEW

**Comment by mouse-reeve** [comment]
When this is ready to go, it will require dropping and re-creating all the existing redis activitysteam, because the data type used to store stream data is changing from a list to an ordered set.

To upgrade, you can run:
```
docker-compose exec web python manage.py erase_streams
docker-compose exec web python manage.py populate_streams
```

It might cause a minute of empty feeds while the stream re-build.

(cc @tofuwabohu )

**Comment by tofuwabohu** [comment]
The stream erasing didn't work out.
Should I have added some redis config stuff for the authentication? Didn't see anything new in  `.env.example`. The instance threw server errors and the logo was switched back to default.

```
 $ docker-compose exec web python manage.py erase_streams
Traceback (most recent call last):
  File "/app/manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/app/bookwyrm/management/commands/erase_streams.py", line 24, in handle
    erase_streams()
  File "/app/bookwyrm/management/commands/erase_streams.py", line 14, in erase_streams
    r.flushall()
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1252, in flushall
    return self.execute_command('FLUSHALL', *args)
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 878, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 892, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 734, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 333, in read_response
    raise error
redis.exceptions.AuthenticationError: Authentication required.
```

**Comment by mouse-reeve** [comment]
oh my bad! the command was being called in python without the redis password. this should fix it: https://github.com/mouse-reeve/bookwyrm/commit/411dd1b14d4bb3995033d2075a8fd76b4fec9529

**Comment by mouse-reeve** [comment]
it might be easier just to run redis with a password in both dev and prod and keep the configuration more consistent 🤔

**Comment by tofuwabohu** [comment]
Worked, thanks :confetti_ball:

**Pull request merged**
