### PR TITLE
I18n wording fixes

### PR DESCRIPTION
**Pull request by mouse-reeve**
Having the Chinese translation makes it a lot easier to see where I've missed things in the templates...

cc @arkhi @GuDzpoz (at your leisure)

### CODE REVIEW

**Comment by mouse-reeve** [comment]
The one translation I added that might be just a bad idea is `"by"` on line 36. This is for the header on book pages, where the title is listed on one line and the list of authors is in a sub-header below. Because the author names is a list of links, I can't put it in the translation block. Some options, if this is way too granular a chunk of English to translate, would be to treat it as "Authors: " instead of part of a sentence fragment? Other ideas welcome

**Comment by arkhi** [comment]
Mmm… Maybe this would be possible:

```html
<ul class="subtitle" aria-label="Authors">
    <li><a href="/author/1" class="author">Jane Doe</a></li>
    <li><a href="/author/2" class="author">Jean Dupont</a></li>
    <li><a href="/author/3" class="author">陈莺</a></li>
</ul>
```

This way, people using screen readers are not presented with a `h2` which is not a header and they have an indication of what the list is about.

**Comment by arkhi** [comment]
Actually, a `dl` would make more sense here, sorry. As you hinted, sighted people might benefit of having the _Term_ displayed too.

```html
<dl class="subtitle">
    <dt>Authors:</dt>
    <dd><a href="/author/1" class="author">Jane Doe</a></dd>
    <dd><a href="/author/2" class="author">Jean Dupont</a></dd>
    <dd><a href="/author/3" class="author">陈莺</a></dd>
</dl>
```

**Comment by arkhi** [comment]
I was also thinking about the linebreaks in the po files. Is this a requirements for Python or Gettext? I found it would help to have all on one line when having to search for specific strings or make replacements. CLI editors probably have ways to wrap lines (nano does) so I wouldn’t expect this to be an issue for developers.

Just my two cents. :)

**Comment by mouse-reeve** [comment]
> I was also thinking about the linebreaks in the po files. Is this a requirements for Python or Gettext? I found it would help to have all on one line when having to search for specific strings or make replacements. CLI editors probably have ways to wrap lines (nano does) so I wouldn’t expect this to be an issue for developers.
> 
> Just my two cents. :)

I found a setting for this! the makemessages command just needs `--no-wrap`, I'll update the shortcut file

**Comment by arkhi** [comment]
Looking at the websites, is there any specific consensus about _[Your shelves]_ vs _My shelves_? I somehow feel I would feel more inclined to click on a _My_ than a _Your_ in the context of an action.

[Your shelves]: https://github.com/mouse-reeve/bookwyrm/blob/2d7e5f76bd742b565606e1593df73b4ac43e7e6d/bookwyrm/templates/layout.html#L58

**Comment by mouse-reeve** [comment]
> Looking at the website, is there any specific consensus about _[Your shelves](https://github.com/mouse-reeve/bookwyrm/blob/2d7e5f76bd742b565606e1593df73b4ac43e7e6d/bookwyrm/templates/layout.html#L58)_ vs _My shelves_? I somehow feel I would feel more inclined to click on a _My_ than a _Your_ in the context of an action.

I've been using "your" but I don't feel strongly about it

**Comment by mouse-reeve** [comment]
I'm going to go ahead and merge this so I don't create conflicts, but feel free to leave additional comments on this PR

**Comment by mouse-reeve** [comment]
@tofuwabohu I made some changes here based on the new locale files, this is all reflected in the 4 available languages in the `main` branch now ❤️

**Comment by arkhi** [comment]
> shelves



>  is there any specific consensus about _[Your shelves](https://github.com/mouse-reeve/bookwyrm/blob/2d7e5f76bd742b565606e1593df73b4ac43e7e6d/bookwyrm/templates/layout.html#L58)_ vs _My shelves_?

I’m currently reading an [article about UX writing principles](https://medium.com/sainsburys-digital-experience/how-to-build-better-digital-experiences-with-ux-writing-principles-3c65fcdbcef8). It explains a few key principles and might give directions if needed.

**Pull request merged**
