### PR TITLE
Makes localname case insensitive

### PR DESCRIPTION
**Pull request by mouse-reeve**
This makes the uniqueness of local users' usernames case insensitive.
Works on #886

### CODE REVIEW

**Comment by mouse-reeve** [comment]
If there are any existing case-insensitive duplicate usernames, this migration will fail. There aren't any on bookwyrm.social, but it's theoretically possible. I can't think of any programmatic way to resolve this, I think it would require having a conversation and reaching a compromise with the affected users. But hopefully no one runs into this issue!

**Comment by tofuwabohu** [comment]
I have one (that I created to test if it's possible). It's a dummy account, what's the easiest way to delete one of them?

**Comment by mouse-reeve** [comment]
if it doesn't have any posts or friends, you should be able to truly delete it from the database using django admin (`/admin/bookwyrm/user/` is a list of users `/admin/bookwyrm/user/<user_id>` if you know the id for that user). You can also change the localname in the django admin if you can't delete

**Comment by tofuwabohu** [comment]
:exploding_head: I always thought you meant the bookwyrm admin settings when you spoke of the django admin interface, never seen the /admin thingy! Guess I have a lot to explore now :D

**Comment by tofuwabohu** [comment]
Alright, couldn't delete it due to the auto-generated shelves but renaming worked :)

**Pull request merged**
