### PR TITLE
Invite request

### PR DESCRIPTION
**Pull request by mouse-reeve**
Give users a form so they can ask for an invite instead of having to dm me and then I miss it and everyone feels bad (or whatever).

Work:
 - [x] Request model
 - [x] Site settings flag for allowing requests
 - [x] Request form
 - [x] Admin flow to grant requests
 - [x] Invite emails
 - [x] Tests

Works on #223

### CODE REVIEW

**Comment by rkingett** [comment]
Could you make this available to all instance admins? I am sure other instance hosts would benefit from this form as well.

**Comment by Flameborn** [comment]
I suspect this will be available to anyone wishing to host their instance.

The good thing about this is that people won't need to hunt for someone who's an admin, nor will you have to expose who's an admin before registering, they will be able to reach admins directly.

Now to figure out why mailGun's not working on my end... 😀

**Comment by mouse-reeve** [comment]
I have a plain text file of email addresses of people who want to join bookwyrm.social, it was time for a change 😂

**Comment by rkingett** [comment]
You also may want to link to the form on the homepage... I found the below,

> BookWyrm is still under development, and it's not as polished, stable, and feature-complete as a production-ready application.
If you'd like to join anyway, please contact the site admin by emailing

**Pull request merged**
